[package]
name = "pendant_watch"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "pendant_watch"
path = "src/main.rs"

[dependencies]
windows = { version = "0.52", features = ["Win32_UI_Input_KeyboardAndMouse"] }
serialport = "4.2"
regex = "1"
crossterm = "0.27"
